knp_paginator:
    page_range: 5

    default_options:
        page_name: page
        page_out_of_range: fix
        default_limit: 10

    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'